# Copyright 2026 Nearby Computing S.L.

apiVersion: v2
name: kafkanotify-operator
description: A Helm chart to distribute the project kafkanotify-operator
type: application
version: 0.2.0
appVersion: "0.1.0"
icon: "https://example.com/icon.png"
